module

public import Mathlib.Analysis.Convex.Basic
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.Analysis.Normed.Lp.MeasurableSpace
public import Mathlib.Geometry.Convex.ConvexSpace.CompactSpaceStdSimplex
public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.Probability.IdentDistrib
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.Probability.Process.HittingTime
public import Mathlib.MeasureTheory.Constructions.Cylinders
public import Mathlib.MeasureTheory.Integral.Indicator
public import Mathlib.Probability.ConditionalProbability
public import Mathlib.Probability.HasLaw
public import Mathlib.MeasureTheory.Measure.Map
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.Algebra.BigOperators.Intervals
public import Mathlib.Analysis.Calculus.Gradient.Basic
public import Mathlib.Analysis.Calculus.LineDeriv.Basic
public import Mathlib.Analysis.Convex.Function
public import Mathlib.Topology.Algebra.Module.ContinuousLinearMap.PiProd
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Order
public import Mathlib.MeasureTheory.Integral.Prod
public import Mathlib.Probability.Kernel.Composition.IntegralCompProd
public import Mathlib.Probability.Distributions.Bernoulli
public import Mathlib.Probability.Distributions.Uniform
public import Mathlib.Probability.Kernel.Composition.MeasureCompProd
public import Mathlib.Topology.Algebra.InfiniteSum.ENNReal
public import Mathlib.InformationTheory.KullbackLeibler.Basic
public import Mathlib.MeasureTheory.Integral.Pi
public import Mathlib.Probability.Kernel.Composition.WithDensity
public import Mathlib.InformationTheory.KullbackLeibler.DataProcessing

/-! # Standalone extraction for `Chase2026Tight.exists_pseudoRegret_ge`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace Learning
end Learning
namespace ProbabilityTheory
end ProbabilityTheory
namespace ENNReal
end ENNReal
namespace Bandits
end Bandits
namespace Chase2026Tight
end Chase2026Tight

-- ═══ Chase2026Tight.Mathlib.Analysis.Convex.Simplex ═══
@[expose] public section
open MeasureTheory
namespace Learning
variable {ι : Type*} [Fintype ι]

/-- The probability simplex `{p | ∀ i, 0 ≤ p i, ∑ i, p i = 1}` of `EuclideanSpace ℝ ι`. -/
def simplex (ι : Type*) [Fintype ι] : Set (EuclideanSpace ℝ ι) :=
  {p | (∀ i, 0 ≤ p i) ∧ ∑ i, p i = 1}

/-- A point of the simplex is a function on `ι`: `p i` is its `i`-th coordinate. -/
instance instCoeFunElemEuclideanSpaceRealSimplexForall : CoeFun (simplex ι) (fun _ ↦ ι → ℝ) := ⟨fun p ↦ (p : EuclideanSpace ℝ ι).ofLp⟩

lemma single_mem_simplex [DecidableEq ι] (i : ι) : EuclideanSpace.single i (1 : ℝ) ∈ simplex ι := sorry

end Learning
end

-- ═══ LeanMachineLearning.SequentialLearning.Algorithm ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning
variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- One round of interaction: an observation, then an action, then a feedback. -/
abbrev Round (𝓞 𝓐 𝓨 : Type*) := 𝓞 × 𝓐 × 𝓨

/-- The observation of a round. -/
def Round.obs (r : Round 𝓞 𝓐 𝓨) : 𝓞 := r.1

/-- The action of a round. -/
def Round.action (r : Round 𝓞 𝓐 𝓨) : 𝓐 := r.2.1

/-- The feedback of a round. -/
def Round.feedback (r : Round 𝓞 𝓐 𝓨) : 𝓨 := r.2.2

/-- History of `n` complete rounds; `n = 0` is the empty history. -/
abbrev Hist (𝓞 𝓐 𝓨 : Type*) (n : ℕ) := Fin n → Round 𝓞 𝓐 𝓨

/-- A stochastic, sequential algorithm.
At each round, it sees an observation in `𝓞`, then takes an action in `𝓐`, and finally receives
feedback in `𝓨`. The action is a random function of the past rounds and the current observation. -/
@[ext]
structure Algorithm (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the action of round `n` given the past rounds and the current observation. -/
  policy : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n × 𝓞) 𝓐
  /-- The policy is a Markov kernel. -/
  [isMarkovKernel_policy : ∀ n, IsMarkovKernel (policy n)]

instance instIsMarkovKernelProdHistPolicy (alg : Algorithm 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (alg.policy n) :=
  alg.isMarkovKernel_policy n

/-- A stochastic environment.
At each round, an observation is drawn prior to the algorithm taking an action. Then the environment
provides feedback based on the observation and the action. -/
@[ext]
structure Environment (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the observation of round `n` given the past rounds. -/
  obs : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n) 𝓞
  /-- Law of the feedback of round `n` given the past rounds, the observation and the action. -/
  feedback : (n : ℕ) → Kernel ((Hist 𝓞 𝓐 𝓨 n × 𝓞) × 𝓐) 𝓨
  /-- The observation kernel is a Markov kernel. -/
  [isMarkovKernel_obs : ∀ n, IsMarkovKernel (obs n)]
  /-- The feedback kernel is a Markov kernel. -/
  [isMarkovKernel_feedback : ∀ n, IsMarkovKernel (feedback n)]

section IsAlgEnvSeq
variable {O : ℕ → Ω → 𝓞} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨} {P : Measure Ω} [IsFiniteMeasure P] {N : ℕ}

/-- History of the algorithm-environment sequence before time `n`: the rounds at
times `0, ..., n - 1`. -/
def history (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) : Hist 𝓞 𝓐 𝓨 n :=
  fun i ↦ (O i ω, A i ω, Y i ω)

/-- An algorithm-environment sequence: a sequence of observations, actions and feedbacks generated
by an algorithm interacting with an environment. -/
structure IsAlgEnvSeq
    (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨)
    (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨)
    (P : Measure Ω) [IsFiniteMeasure P] : Prop where
  /-- The observation sequence is measurable. -/
  measurable_obs n : Measurable (O n) := by fun_prop
  /-- The action sequence is measurable. -/
  measurable_action n : Measurable (A n) := by fun_prop
  /-- The feedback sequence is measurable. -/
  measurable_feedback n : Measurable (Y n) := by fun_prop
  /-- The observation at time `n` has the correct conditional distribution given the history. -/
  hasCondDistrib_obs n :
    HasCondDistrib (O n) (history O A Y n) (env.obs n) P
  /-- The action at time `n` has the correct conditional distribution given the history and the
  observation at time `n`. -/
  hasCondDistrib_action n :
    HasCondDistrib (A n) (fun ω ↦ (history O A Y n ω, O n ω)) (alg.policy n) P
  /-- The feedback at time `n` has the correct conditional distribution given the history, the
  observation and the action at time `n`. -/
  hasCondDistrib_feedback n :
    HasCondDistrib (Y n) (fun ω ↦ ((history O A Y n ω, O n ω), A n ω)) (env.feedback n) P

end IsAlgEnvSeq
end Learning
end

-- ═══ Chase2026Tight.LeanMachineLearning.SequentialLearning.ObliviousEnv ═══
@[expose] public section
open MeasureTheory ProbabilityTheory
namespace Learning
variable {𝓞 𝓐 𝓨 : Type*} [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]

/-- The feedback kernels of the environment do not read the action of the current round: the
feedback of a round is drawn given the past rounds and the current observation only (the
environment is *non-anticipating*, as an adversary committing its losses before the action). -/
def Environment.FeedbackIgnoresAction (env : Environment 𝓞 𝓐 𝓨) : Prop :=
  ∀ n, ∃ κ : Kernel (Hist 𝓞 𝓐 𝓨 n × 𝓞) 𝓨, env.feedback n = κ.comap Prod.fst measurable_fst

/-- The feedbacks of the environment lie in the set `s`, almost surely. -/
def Environment.FeedbackIn (env : Environment 𝓞 𝓐 𝓨) (s : Set 𝓨) : Prop :=
  ∀ n p, ∀ᵐ y ∂(env.feedback n p), y ∈ s

end Learning
end

-- ═══ LeanMachineLearning.SequentialLearning.Comap ═══
@[expose] public section
open MeasureTheory ProbabilityTheory
namespace Learning
variable {𝓞 𝓞' 𝓞'' 𝓐 𝓐' 𝓐'' 𝓨 𝓨' 𝓨'' Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓞' : MeasurableSpace 𝓞'} {m𝓞'' : MeasurableSpace 𝓞''} {m𝓐 : MeasurableSpace 𝓐} {m𝓐' : MeasurableSpace 𝓐'} {m𝓐'' : MeasurableSpace 𝓐''} {m𝓨 : MeasurableSpace 𝓨} {m𝓨' : MeasurableSpace 𝓨'} {m𝓨'' : MeasurableSpace 𝓨''} {mΩ : MeasurableSpace Ω} {fo : 𝓞 → 𝓞'} {fa : 𝓐 → 𝓐'} {fy : 𝓨 → 𝓨'} {go : 𝓞' → 𝓞''} {ga : 𝓐' → 𝓐''} {gy : 𝓨' → 𝓨''}
section Comap

/-- The algorithm with observations in `𝓞'` and feedbacks in `𝓨'` obtained from
`alg : Algorithm 𝓞 𝓐 𝓨` by transforming the pair (past rounds, current observation) by `F n` at
each round `n` before applying the policy of `alg`.

This is the primitive transport operation on algorithms: `Algorithm.comapObs` and
`Algorithm.comapFeedback` are the special cases in which `F n` is a round-wise map of the
observation and of the feedback. -/
def Algorithm.comap (alg : Algorithm 𝓞 𝓐 𝓨)
    (F : (n : ℕ) → Hist 𝓞' 𝓐 𝓨' n × 𝓞' → Hist 𝓞 𝓐 𝓨 n × 𝓞) (hF : ∀ n, Measurable (F n)) :
    Algorithm 𝓞' 𝓐 𝓨' where
  policy n := (alg.policy n).comap (F n) (hF n)

end Comap
end Learning
end

-- ═══ Chase2026Tight.LeanMachineLearning.SequentialLearning.PartialFeedback ═══
@[expose] public section
open MeasureTheory ProbabilityTheory
namespace Learning
variable {𝓞 𝓐 𝓨 𝓦 𝓩 : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {m𝓦 : MeasurableSpace 𝓦} {m𝓩 : MeasurableSpace 𝓩}

/-- The round `r = (o, a, y)` in which the feedback is replaced by the partial feedback `g r`, a
function of the whole round: `(o, a, g (o, a, y))`. -/
def Round.partialFeedback (g : Round 𝓞 𝓐 𝓨 → 𝓦) (r : Round 𝓞 𝓐 𝓨) : Round 𝓞 𝓐 𝓦 :=
  (r.obs, r.action, g r)

/-- A history seen through the partial feedback map `g`: the feedback of each round `r` is
replaced by `g r`. -/
def Hist.partialFeedback (g : Round 𝓞 𝓐 𝓨 → 𝓦) {n : ℕ} (h : Hist 𝓞 𝓐 𝓨 n) : Hist 𝓞 𝓐 𝓦 n :=
  fun i ↦ Round.partialFeedback g (h i)

@[fun_prop]
lemma Hist.measurable_partialFeedback {g : Round 𝓞 𝓐 𝓨 → 𝓦} (hg : Measurable g) (n : ℕ) :
    Measurable (Hist.partialFeedback g (n := n)) := sorry

/-- The algorithm with feedback in `𝓨` obtained from an algorithm `alg` with feedback in `𝓦` by
observing `g (o, a, y)` of each round `(o, a, y)` of the history: the transport of `alg` along
the round-wise history map `Hist.partialFeedback g`. -/
noncomputable def Algorithm.comapPartialFeedback (alg : Algorithm 𝓞 𝓐 𝓦)
    (g : Round 𝓞 𝓐 𝓨 → 𝓦) (hg : Measurable g := by fun_prop) : Algorithm 𝓞 𝓐 𝓨 :=
  alg.comap (fun _ p ↦ (Hist.partialFeedback g p.1, p.2))
    fun n ↦ ((Hist.measurable_partialFeedback hg n).comp measurable_fst).prodMk measurable_snd

end Learning
end

-- ═══ Chase2026Tight.LeanMachineLearning.Online.Bandit.Adversarial ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset Learning
namespace Bandits
variable {𝓞 α 𝓨 𝓩 : Type*} {m𝓞 : MeasurableSpace 𝓞} {mα : MeasurableSpace α} {m𝓨 : MeasurableSpace 𝓨} {m𝓩 : MeasurableSpace 𝓩}

/-- The *bandit feedback* of a round whose feedback is a loss vector: the loss of the pulled
arm. -/
def banditFeedback (r : Round 𝓞 α (α → 𝓨)) : 𝓨 := r.feedback r.action

section Measurability
variable [Countable α] [MeasurableSingletonClass α]

@[fun_prop]
lemma measurable_banditFeedback : Measurable (banditFeedback (𝓞 := 𝓞) (α := α) (𝓨 := 𝓨)) := sorry

end Measurability
end Bandits
namespace Learning
open Bandits
variable {𝓞 α 𝓨 𝓩 𝓩' : Type*} {m𝓞 : MeasurableSpace 𝓞} {mα : MeasurableSpace α} {m𝓨 : MeasurableSpace 𝓨} {m𝓩 : MeasurableSpace 𝓩} {m𝓩' : MeasurableSpace 𝓩'} [Countable α] [MeasurableSingletonClass α]

/-- A learner with bandit feedback run against loss vectors: the algorithm with feedback the loss
vector of all arms, of which it sees only the loss of the arm it pulled. -/
noncomputable def Algorithm.comapBanditFeedback (alg : Algorithm 𝓞 α 𝓨) :
    Algorithm 𝓞 α (α → 𝓨) :=
  alg.comapPartialFeedback banditFeedback measurable_banditFeedback

end Learning
end

-- ═══ Chase2026Tight.LeanMachineLearning.Online.Bandit.ExpertAdvice ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset Learning
namespace Bandits
variable {α ι Ω : Type*} [Fintype α]

/-- The advice of the experts `ι`: a probability vector over the arms `α` for each expert. -/
abbrev Advice (ι α : Type*) [Fintype α] := ι → simplex α

/-- Deterministic advice `e : ι → α` (expert `j` names the arm `e j`) as Dirac advice vectors. -/
noncomputable def diracAdvice [DecidableEq α] (e : ι → α) : Advice ι α :=
  fun j ↦ ⟨EuclideanSpace.single (e j) 1, single_mem_simplex (e j)⟩

/-- The loss `∑_a π j a ℓ a` of expert `j` under the advice `π` and the loss vector `ℓ`: the
expected loss of an arm drawn from its advice vector. -/
def expertLoss (π : Advice ι α) (ℓ : α → ℝ) (j : ι) : ℝ := ∑ a, π j a * ℓ a

/-- The regret over `T` rounds of the arms `a` against the expert `j`, for the advice `π` and the
loss vectors `ℓ`: `∑_{t < T} ℓ t (a t) - ∑_{t < T} expertLoss (π t) (ℓ t) j`. -/
noncomputable def adviceRegret (π : ℕ → Advice ι α) (a : ℕ → α) (ℓ : ℕ → α → ℝ) (T : ℕ)
    (j : ι) : ℝ :=
  ∑ t ∈ range T, ℓ t (a t) - ∑ t ∈ range T, expertLoss (π t) (ℓ t) j

variable {mΩ : MeasurableSpace Ω}

/-- The pseudo-regret after `T` rounds of a run with advice `O`, arms `A` and loss vectors `Y`:
`max_j E[∑_{t < T} (Y t (A t) - expertLoss (O t) (Y t) j)]`, the largest expected regret of the
run against an expert. -/
noncomputable def expertPseudoRegret (P : Measure Ω) (O : ℕ → Ω → Advice ι α) (A : ℕ → Ω → α)
    (Y : ℕ → Ω → α → ℝ) (T : ℕ) : ℝ :=
  ⨆ j, P[fun ω ↦ adviceRegret (fun t ↦ O t ω) (fun t ↦ A t ω) (fun t ↦ Y t ω) T j]

end Bandits
end

-- ═══ Chase2026Tight.CIM2026.Theorem6_1 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Learning Bandits Real
universe u v w
namespace Chase2026Tight

/-- **Theorem 6.1** (Chase, Ito, Mehalel 2026). There is a universal constant `c > 0` such that
for all numbers of arms `K ≥ 3` and experts `N ≥ 2K`, every horizon `T ≥ K ln(N / K)` and every
learner for the bandit with expert advice, there is an adaptive adversary (whose losses do not
depend on the arm pulled in the current round) with losses in `{0, 1}`
under which the pseudo-regret of the learner after `T` rounds is at least
`c √(T K log(N / K))`. The paper states it for positive `K`; it is false for `K = 1` (every learner
has pseudo-regret `0`) and the proof needs `K ≥ 3` (the reduced setting has
`k = ⌊(K - 1) / 2⌋ ≥ 1` batches). -/
theorem exists_pseudoRegret_ge :
    ∃ c : ℝ, 0 < c ∧ ∀ (K N T : ℕ), 3 ≤ K → 2 * K ≤ N → K * log (N / K) ≤ T →
      ∀ alg : Algorithm (Fin N → Fin K) (Fin K) ℝ,
      ∃ adv : Environment (Fin N → Fin K) (Fin K) (Fin K → ℝ),
        adv.FeedbackIgnoresAction ∧ adv.FeedbackIn (Set.univ.pi fun _ ↦ {0, 1}) ∧
        ∀ {Ω : Type u} {_mΩ : MeasurableSpace Ω} (P : Measure Ω) [IsProbabilityMeasure P]
          (O : ℕ → Ω → Fin N → Fin K) (A : ℕ → Ω → Fin K) (Y : ℕ → Ω → Fin K → ℝ),
          IsAlgEnvSeq O A Y alg.comapBanditFeedback adv P →
            c * √(T * K * log (N / K)) ≤
              expertPseudoRegret P (fun t ω ↦ diracAdvice (O t ω)) A Y T := sorry

end Chase2026Tight
end
