module

public import Mathlib.Probability.Distributions.Bernoulli
public import Mathlib.Probability.Distributions.Uniform
public import Mathlib.Probability.Kernel.Composition.MeasureCompProd
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.Probability.Process.HittingTime
public import Mathlib.MeasureTheory.Constructions.Cylinders
public import Mathlib.MeasureTheory.Integral.Indicator
public import Mathlib.Probability.ConditionalProbability
public import Mathlib.Probability.HasLaw
public import Mathlib.Probability.IdentDistrib
public import Mathlib.MeasureTheory.Measure.Map
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.Algebra.BigOperators.Intervals
public import Mathlib.Analysis.Calculus.Gradient.Basic
public import Mathlib.Analysis.Calculus.LineDeriv.Basic
public import Mathlib.Analysis.Convex.Function
public import Mathlib.Topology.Algebra.Module.ContinuousLinearMap.PiProd
public import Mathlib.Analysis.Convex.Basic
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.Analysis.Normed.Lp.MeasurableSpace
public import Mathlib.Geometry.Convex.ConvexSpace.CompactSpaceStdSimplex
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Order
public import Mathlib.InformationTheory.KullbackLeibler.Basic
public import Mathlib.MeasureTheory.Integral.Pi
public import Mathlib.Probability.Kernel.Composition.WithDensity

/-! # Standalone extraction for `Chase2026Tight.klDiv_mixture_pi_roundLaw_le`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace Learning
end Learning
namespace Bandits
end Bandits
namespace ENNReal
end ENNReal
namespace Chase2026Tight
end Chase2026Tight
namespace InformationTheory
end InformationTheory

-- ═══ Chase2026Tight.CIM2026.Setting ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Learning Bandits Finset
open scoped ENNReal ENat
universe u
namespace Chase2026Tight

/-- The arms of the reduced setting: arm `0` (`none`) and the two arms `(u, false)`, `(u, true)`
of each batch `u`. -/
def Arm (k : ℕ) := Option (Fin k × Bool)

/-- The experts: expert `0` (`none`) and the experts `(u, v)`, `v ∈ [n]`, of each batch `u`. -/
def Expert (k n : ℕ) := Option (Fin k × Fin n)

variable {k n : ℕ}

instance instFintypeArm : Fintype (Arm k) := inferInstanceAs (Fintype (Option (Fin k × Bool)))

instance instMeasurableSpaceArm : MeasurableSpace (Arm k) := ⊤

instance instDiscreteMeasurableSpaceArm : DiscreteMeasurableSpace (Arm k) := ⟨fun _ ↦ trivial⟩

instance instFintypeExpert : Fintype (Expert k n) := inferInstanceAs (Fintype (Option (Fin k × Fin n)))

/-- Arm `0`. -/
def Arm.zero : Arm k := none

/-- The arm `(u, b)` of batch `u`. -/
def Arm.ofBatch (u : Fin k) (b : Bool) : Arm k := some (u, b)

/-- Whether the arm `a` belongs to batch `u`. -/
def Arm.inBatch (a : Arm k) (u : Fin k) : Bool :=
  match (a : Option (Fin k × Bool)) with
  | none => false
  | some (u', _) => decide (u = u')

/-- Expert `0`. -/
def Expert.zero : Expert k n := none

/-- The expert `(u, v)` of batch `u`. -/
def Expert.mk (u : Fin k) (v : Fin n) : Expert k n := some (u, v)

/-- The advice bits: one bit for each expert `(u, v)`. -/
abbrev Bits (k n : ℕ) := Fin k → Fin n → Bool

/-- The advice given by the bits `b`: expert `(u, v)` advises arm `(u, b u v)`, expert `0`
advises arm `0`. -/
def adviceOf (b : Bits k n) : Expert k n → Arm k := fun j ↦
  match (j : Option (Fin k × Fin n)) with
  | none => Arm.zero
  | some (u, v) => Arm.ofBatch u (b u v)

/-- The bits of an advice: the arm advised by expert `(u, v)` is `(u, bitsOf e u v)` (with the
convention `bitsOf e u v = false` if the advice is not an arm of batch `u`). -/
def bitsOf (e : Expert k n → Arm k) : Bits k n := fun u v ↦
  match (e (Expert.mk u v) : Option (Fin k × Bool)) with
  | none => false
  | some (_, b) => b

/-- The uniform law on the advice bits. -/
noncomputable def uniformBits (k n : ℕ) : Measure (Bits k n) :=
  (PMF.uniformOfFintype (Bits k n)).toMeasure

/-- The Bernoulli law on `Bool` giving probability `p` to `true` (`p` is clamped to `[0, 1]`). -/
noncomputable def bern (p : ℝ) : Measure Bool :=
  bernoulliMeasure true false (Set.projIcc 0 1 zero_le_one p)

/-- The randomness used to draw the losses of a round: a bit `z` (loss of arm `0` is `1` iff
`z`), a uniform bit for each batch (the correct arm of the batch under `S_0`), and a bit `f`
with law `Ber(1/2 - ε)` (under `S_(u, v)`, the arm advised by `(u, v)` is incorrect iff `f`). -/
noncomputable def lossRandomness (k : ℕ) (ε : ℝ) : Measure (Bool × (Fin k → Bool) × Bool) :=
  (bern (1 / 2 - ε / 2)).prod
    (((PMF.uniformOfFintype (Fin k → Bool)).toMeasure).prod (bern (1 / 2 - ε)))

/-- The correct arm of batch `u` under `S_θ`, given the advice `e` and the randomness `r`. -/
def correctArm (θ : Expert k n) (e : Expert k n → Arm k) (r : Bool × (Fin k → Bool) × Bool)
    (u : Fin k) : Bool :=
  match (θ : Option (Fin k × Fin n)) with
  | none => r.2.1 u
  | some (u', v) => if u = u' then xor (bitsOf e u' v) r.2.2 else r.2.1 u

/-- The losses of the arms under `S_θ`, given the advice `e` and the randomness `r`: arm `0` has
loss `1` iff `r.1`, and in batch `u` the correct arm has loss `0` and the other arm loss `1`. -/
def lossOf (θ : Expert k n) (e : Expert k n → Arm k) (r : Bool × (Fin k → Bool) × Bool) :
    Arm k → ℝ := fun a ↦
  match (a : Option (Fin k × Bool)) with
  | none => if r.1 then 1 else 0
  | some (u, b) => if b = correctArm θ e r u then 0 else 1

/-- The law of the losses of a round under `S_θ`, given the advice `e`. -/
noncomputable def lossLaw (ε : ℝ) (θ : Expert k n) (e : Expert k n → Arm k) :
    Measure (Arm k → ℝ) :=
  (lossRandomness k ε).map (lossOf θ e)

/-- The loss kernel of `S_θ`: law of the losses given the advice. -/
noncomputable def lossKernel (ε : ℝ) (θ : Expert k n) : Kernel (Expert k n → Arm k) (Arm k → ℝ) :=
  Kernel.ofFunOfCountable (lossLaw ε θ)

/-- The law of the advice of the first round: uniform bits. -/
noncomputable def initAdvice (k n : ℕ) : Measure (Expert k n → Arm k) :=
  (uniformBits k n).map adviceOf

/-- Advice and losses of a round. -/
abbrev AdvLoss (k n : ℕ) := (Expert k n → Arm k) × (Arm k → ℝ)

/-- The law of the advice and losses of a round under `S_θ` when the advice is fresh: the law
of the first round, `P_θ` in the paper. -/
noncomputable def roundLaw (ε : ℝ) (θ : Expert k n) : Measure (AdvLoss k n) :=
  initAdvice k n ⊗ₘ lossKernel ε θ

end Chase2026Tight
end

-- ═══ Chase2026Tight.CIM2026.Lemma4_1 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory InformationTheory Learning Bandits
open scoped ENNReal
namespace Chase2026Tight

set_option linter.unusedVariables false in
/-- **Lemma 4.1** (Chase, Ito, Mehalel 2026; Ito et al. 2024). In the two-batch game (`k = 1`),
for `0 < ε ≤ 0.1`, `T ≥ 1` and `n ≥ 1`,
`KL((1/n) ∑_v P_(1, v)^T ‖ P_0^T) ≤ ((1 + 4 ε²)^T - 1) / n`. The hypothesis `T ≥ 1` of the paper
is not needed (the bound holds for `T = 0`); it is kept in the statement, as in the paper. -/
@[nolint unusedArguments]
theorem klDiv_mixture_pi_roundLaw_le {n : ℕ} (hn : 1 ≤ n) {ε : ℝ} (hε : ε ∈ Set.Ioc 0 0.1)
    {T : ℕ} (hT : 1 ≤ T) :
    klDiv ((n : ℝ≥0∞)⁻¹ • ∑ v : Fin n, Measure.pi fun _ : Fin T ↦ roundLaw ε (Expert.mk 0 v))
        (Measure.pi fun _ : Fin T ↦ roundLaw (k := 1) ε Expert.zero) ≤
      ENNReal.ofReal (((1 + 4 * ε ^ 2) ^ T - 1) / n) := sorry

end Chase2026Tight
end
